credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "SonarScanner Creds"
          id: "sonar"
          password: "{AQAAABAAAAAQCbi/CAZCUQi5MLnKEXn2mCOQPptYYC40oINwOVC9O3o=}"
          scope: GLOBAL
          username: "admin"
      - usernamePassword:
          description: "Tower creds"
          id: "tower"
          password: "{AQAAABAAAAAQkCTOnAeyQ8I0r2AEsJx2YHOlJha74+DfjPLAO3HoYHU=}"
          scope: GLOBAL
          username: "admin"
      - usernamePassword:
          id: "149470a9-db23-4700-b5d6-1f00762a98c7"
          password: "{AQAAABAAAAAQe/h+nHFDWCvIY5Hr4Z8pR8wyhmKjC8mIdZ8UZTUGCVA=}"
          scope: GLOBAL
          username: "jenkins"
      - usernamePassword:
          id: "sonarqube"
          password: "{AQAAABAAAAAQaehgz/g13dOjwNn0fZqYIBnhipAfMZsh1GsvjjMRaF0=}"
          scope: GLOBAL
          username: "admin"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "myView"
        - "timezone"
        - favoriting:
            autofavoriteEnabled: true
        - "mailer"
        - "favorite"
        - preferredProvider:
            providerId: "default"
  slaveAgentPort: 0
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
    globalColorMapName: "xterm"
  ansibleTowerGlobalConfig:
    towerInstallation:
    - enableDebugging: true
      towerCredentialsId: "149470a9-db23-4700-b5d6-1f00762a98c7"
      towerDisplayName: "JuiceShop Tower"
      towerTrustCert: true
      towerURL: "https://tower.vagrant.local"
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jenkins.vagrant.local:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  globalSettings:
    failOnCorrupt: false
    noAuthors: false
    quietMode: false
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins.vagrant.local:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - name: "sonarqube"
      serverUrl: "http://sonar.vagrant.local:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
tool:
  ansibleInstallation:
    installations:
    - name: "Ansible"
  git:
    installations:
    - home: "git"
      name: "git"
  sonarRunnerInstallation:
    installations:
    - name: "sonarqube"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.4.0.2170"