---
- name: Deploy Application to EC2 Instances
  hosts: all
  gather_facts: true
  roles:
  - role: geerlingguy.nodejs
    vars:
      nodejs_version: "10.x"
  
  tasks:
  - name: Extract download
    unarchive:
      src: https://github.com/bkimminich/juice-shop/releases/download/v8.6.2/juice-shop-8.6.2_node10_linux_x64.tgz
      remote_src: true
      dest: /usr/local/
    register: app_download
    tags:
      - extract

  - name: Install Forever
    npm: 
      name: forever 
      global: yes 
      state: present
    tags:
      - run_app

  # - name: Check list of running Node.js apps.
  #   command: forever list
  #   register: forever_list
  #   changed_when: false
  #   tags:
  #     - run_app

  # - name: Debug forever_list
  #   debug:
  #     msg: "Forevver List: {{ forever_list }}"
  #   tags:
  #     - run_app

  # - name: Start example Node.js app.
  #   command: "forever start /usr/local/juice-shop_8.6.2/app.js"
  #   # when: "forever_list.stdout.find(/usr/local/juice-shop_8.6.2/ + 'app.js') == -1"
  #   tags:
  #     - run_app

  - name: Run application
    become: true
    command: 
      cmd: "forever start app.js"
      chdir: /usr/local/juice-shop_8.6.2/
    tags:
      - run_app


  tags:
    - app_deploy
    - webservers
    - devsecops

