---
## @todo use inisghts role
- name: Unsubscribe from RHSM and Insights
  hosts: all
  become: false
  gather_facts: false

  tasks:
  - name: Remove from RHSM
    redhat_subscription:
      state: absent
      pool_ids:
        - "{{ rhsm_pool_id }}"
