---
- name: Deploy Application to WebServers
  hosts: all
  roles:
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
    vars:
      - java_packages: 
        - java-1.8.0-openjdk-devel
  tags:
    - webservers
    - devsecops

