---
- name: Deploy Application to EC2 Instances
  hosts: all
  gather_facts: true

  roles:
  - role: geerlingguy.nodejs
    vars:
      nodejs_version: "10.x"

  environment:
    NODE_ENV: quiet

  tags:
  - app_deploy
  - webservers
  - devsecops

  tasks:
  - name: debug facts stored from tower host
    debug:
      var: hostvars['tower']['new_pkg_version']
    tags:
    - app-deploy
    - debug-version

  - name: Extract download
    unarchive:
      src: "{{ app_rel_uri }}"
      remote_src: true
      dest: /usr/local/
    register: app_download
    tags:
    - extract

  - name: Download JuiceShop config file
    get_url:
      url: "{{ app_custom_config }}"
      dest: "{{ node_app_dir }}config/devsecops.yml"
      force: true
    tags:
    - get_config

  - name: Install Forever
    npm:
      name: forever
      global: yes
      state: present
    tags:
    - run_app

  - name: Force NodeJS to bind to IPV4
    replace:
      path: "{{ node_app_dir }}server.js"
      regexp: '^.*\bserver\.listen\b.*$'
      replace: server.listen(process.env.PORT || config.get('server.port'), "0.0.0.0", () => {
    tags:
    - deploy-app
    - ipv4
      
  - name: Check list of running Node.js apps.
    command: forever list
    register: forever_list
    changed_when: false
    tags:
    - run-app

  - name: Run application
    command: forever start app.js
    args:
      chdir: "{{ node_app_dir }}"
    when: "forever_list.stdout.find('app.js') == -1"
    tags:
    - run-app
