---
- name: Deploy Application to EC2 Instances
  hosts: all
  gather_facts: true
  environment: 
    NODE_ENV: "devsecops"
  roles:
  - role: geerlingguy.nodejs
    vars:
      nodejs_version: "10.x"
    
  
  tasks:
  - name: Extract download
    unarchive:
      src: "{{ app_rel_uri }}"
      remote_src: true
      dest: /usr/local/
    register: app_download
    tags:
      - extract
  
  - name: Download DevSecOps JuiceShop config file
    get_url: 
      url: "{{ app_custom_config }}"
      dest: "{{ node_app_dir }}config/devsecops.yml"
    tags:
      - get_config

  - name: Install Forever
    npm: 
      name: forever 
      global: yes 
      state: present
    tags:
      - run_app

  - name: Force NodeJS to bind to IPV4
    replace:
      path: "{{ node_app_dir }}server.js"
      regexp: '^.*\bserver\.listen\b.*$'
      replace:  server.listen(process.env.PORT || config.get('server.port'), "0.0.0.0", () => {
    tags:
      - deploy-app
      - ipv4

  - name: Check list of running Node.js apps.
    command: forever list
    register: forever_list
    changed_when: false
    tags:
      - run_app

  - name: Run application
    become: true
    shell: 
      cmd: "NODE_ENV=devsecops && forever start app.js"
      chdir: "{{ node_app_dir }}"
    environment: 
      NODE_ENV: "devsecops"
    when: "forever_list.stdout.find('app.js') == -1"
    tags:
      - run_app

  tags:
    - app_deploy
    - webservers
    - devsecops
