---
- name: Unsubscribe from RHSM and Insights
  hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Remove from Insights
    package:
      name: insights-client
      state: absent

  - name: Remove from RHSM
    redhat_subscription:
      state: absent

- name: Terminate instances that were previously launched
  hosts: all
  gather_facts: false
  become: false

  tasks:
  - name: Gather EC2 Facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
    register: ec2_instances
    delegate_to: localhost

  - name: debug ec2 instances
    debug:
      var: ec2_instances
    delegate_to: localhost
  # - name: Teardown EC2 Instances
  #   ec2:
  #     state: 'absent'
  #     region: "{{ ec2_region }}"
  #     instance_ids: '{{ item.instance_id }}'
  #   loop: '{{ ec2_instances.instances }}'