---
# TODO get F5 IP from facts
- name: Create EC2 Security Group
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
  - name: Create security group
    ec2_group:
      name: "{{ ec2_sg_name }}"
      description: "DevSecOps Demo Security Group"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: 108.128.213.140/32
          # cidr_ip: 0.0.0.0/0