---
- name: Deploy EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  # - name: Create an EC2 key
  #   ec2_key:
  #     aws_access_key: "{{ aws_access_key_id }}"
  #     aws_secret_key: "{{ aws_secret_access_key }}"
  #     name: "devsecopskey"
  #     region: "{{ region }}"
  #   register: ec2_key
  # - name: Save private key (PEM file)
  #   copy: 
  #     content: "{{ec2_key.key.private_key}}" 
  #     dest: lookup('env', 'HOME')/.ssh/devsecopskey.pem
  #     mode: 0600
  #   when: ec2_key.changed
  - name: Create EC Instances
    ec2:
      key_name: "{{ ec2_keyname }}"
      group: "{{ ec2_sg_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_ami }}"
      wait: true
      region: "{{ ec2_region }}"
      count: "{{ ec2_count }}"
      count_tag:
        Name: ec2_devsecops
      instance_tags:
        Name: ec2_devsecops
        function: webserver
      wait_timeout: 500
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: 
      hostname: "{{ item.public_ip }}"
      ansible_hostname: "{{ item.public_dns_name }}"
      groupname: ec2_devsecops_hosts
    loop: "{{ ec2.instances }}"

  # - name: Wait for SSH to come up
  #   delegate_to: "{{ item.public_dns_name }}"
  #   wait_for_connection:
  #     delay: 60 
  #     timeout: 320
  #   loop: "{{ ec2.instances }}"
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started 
    loop: "{{ ec2.instances }}"

- name: Gather Facts from EC2 Hosts
  user: ec2-user
  hosts: ec2_devsecops_hosts
  gather_facts: true