---
- name: Create EC2 Security Group
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
  - name: Gather EC2 facts
    ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        "tag:function": "{{ ec2_f5_tag }}"
    register: ec2
    tags:
     - ec2-sg-deploy
     - ec2_f5_facts

  - name: Create Facts for F5 configuration
    set_fact:
      f5_private_ip: "{{ item['private_ip_address'] }}"
      cacheable: true
    loop: "{{ ec2.instances }}"
    tags:
     - ec2_sg_deploy
     - ec2_sg_set_fact

  - name: Create security group
    ec2_group:
      name: "{{ ec2_sg_name }}"
      description: "JuiceShop Security Group"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: "{{ hostvars['localhost']['f5_private_ip'] + '/32'}}"
    tags:
     - ec2_sg_deploy
     - ec2_sg_create