---
- name: Deploy EC2 Instances
  hosts: all
  become: false
  gather_facts: false
  vars_files:
    - ./local/vars/vault_aws_vars.yml
  vars:
    region: eu-west-1
    instance_type: t2.micro
    ami: ami-0202869bdd0fc8c75

  tasks:
  - name: Create security group
    ec2_group:
      # aws_access_key: "{{ aws_access_key_id }}"
      # aws_secret_key: "{{ aws_secret_access_key }}"
      name: "devsecopssg"
      description: "DevSecOps Demo Security Group"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
  # - name: Create an EC2 key
  #   ec2_key:
  #     aws_access_key: "{{ aws_access_key_id }}"
  #     aws_secret_key: "{{ aws_secret_access_key }}"
  #     name: "devsecopskey"
  #     region: "{{ region }}"
  #   register: ec2_key
  # - name: Save private key (PEM file)
  #   copy: 
  #     content: "{{ec2_key.key.private_key}}" 
  #     dest: lookup('env', 'HOME')/.ssh/devsecopskey.pem
  #     mode: 0600
  #   when: ec2_key.changed
  - name: Create an ec2 instance
    ec2:
      # aws_access_key: "{{ aws_access_key_id }}"
      # aws_secret_key: "{{ aws_secret_access_key }}"
      key_name: devsecopskey
      group: devsecopssg
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      count: 3 # default
      count_tag:
        Name: ec2_devsecops
      instance_tags:
        Name: ec2_devsecops
    register: ec2
  # - name: Save IP to inventory file
  #   lineinfile:
  #     dest: "{{hosts_file}}"
  #     insertafter: '\[webservers\]'
  #     line: "{{item.private_ip}}"
  #   with_items: "{{ec2.instances}}"