---
- name: Terminate EC2 WebServers
  hosts: all
  gather_facts: false

  tasks:
  - name: Remove from RHSM
    redhat_subscription:
      state: absent
    with_inventory_hostnames:
      - all

  - name: Remove from Insights
    command: >
      insights-client  --unregister

  - name: Terminate instances that were previously launched
    ec2:
      state: 'absent'
      region: "{{ ec2_region }}"
      instance_ids: '{{ item.instance_id }}'
    with_inventory_hostnames:
      - all
    delegate_to: localhost
    connection: local
  # - name: Add all instances to host group
  #   add_host: 
  #     hostname: "{{ item.public_dns_name }}"
  #     # ansible_hostname: "{{ item.public_dns_name }}"
  #     groupname: ec2_devsecops_host
  #   loop: "{{ ec2.instances }}"

  # # - name: Wait for SSH to come up
  # #   delegate_to: "{{ item.public_dns_name }}"
  # #   wait_for_connection:
  # #     delay: 60
  # #     timeout: 320
  # #   loop: "{{ ec2.instances }}"
  
  # - name: Wait for SSH to come up
  #   wait_for:
  #     host: "{{ item.public_ip }}"
  #     port: 22
  #     state: started 
  #   loop: "{{ ec2.instances }}"
