---
- name: Terminate instances that were previously launched
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
  - name: Gather EC2 Facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
    register: ec2_instances

  # - name: debug ec2 instances
  #   debug:
  #     msg: "TAGS: {{ item.tags.Name }}"
  #   loop: "{{ ec2_instances.instances }}"
  #   when: item.tags.Name == "ec2_devsecops"
  #   delegate_to: localhost
    
  - name: Teardown EC2 Instances
    ec2:
      state: 'absent'
      region: "{{ ec2_region }}"
      instance_ids: '{{ item.instance_id }}'
    loop: '{{ ec2_instances.instances }}'