---
- name: Deploy EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    ec2:
      key_name: "{{ ec2_keyname }}"
      group: "{{ ec2_sg_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_ami }}"
      wait: true
      region: "{{ ec2_region }}"
      count: "{{ ec2_count }}"
      count_tag:
        Name: ec2_devsecops
      exact_count: "{{ ec2_count }}"
      instance_tags:
        Name: ec2_devsecops
        function: webserver
      wait_timeout: 500
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: 
      hostname: "{{ item.public_dns_name }}"
      # ansible_hostname: "{{ item.public_dns_name }}"
      groupname: ec2_devsecops_hosts
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started 
    loop: "{{ ec2.instances }}"
