---
- name: Terminate EC2 WebServers
  hosts: all
  become: true

  tasks:
## TODO proper tests for insights client
  - name: Remove from Insights
    package:
      name: insights-client
      state: absent

  - name: Remove from RHSM
    redhat_subscription:
      state: absent

- name: Terminate instances that were previously launched
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
  - ec2_instance_facts:
      region: "{{ ec2_region }}"
    register: ec2_instances

  - name: debug facts
    debug:
      msg: " InstancesSS {{ item.instance_id }}"
    loop: '{{ ec2_instances.instances }}'

  - name: Teardown EC2 Instances
    ec2:
      state: 'absent'
      region: "{{ ec2_region }}"
      instance_ids: '{{ item.instance_id }}'
    loop: '{{ ec2_instances.instances }}'