---
- name: Terminate instances that were previously launched
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
  - name: Gather EC2 Facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      # filters:
      #   "tag:function": "{{ ec2_webserver_tag }}"
    register: ec2_instances
    
  - name: Teardown EC2 Web Servers
    ec2_instance:
      state: "{{ ec2_webserver_teardown_state }}"
      region: "{{ ec2_region }}"
      filters:
        "tag:function": "{{ ec2_webserver_tag }}"

  - name: Teardown Firewall
    ec2_instance:
      state: "{{ ec2_f5_teardown_state }}"
      region: "{{ ec2_region }}"
      filters:
        "tag:function": "{{ ec2_f5_tag }}"