---
# TODO add checks for vars and state if ec2 instances
- name: Create EC2 Security Group
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
  - name: Gather EC2 facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
    register: ec2
    tags:
     - ec2_facts

  - name: Check state of ec2 instance
    debug:
      var: item
    when: item.tags.function == ec2_f5_tag
    loop: "{{ ec2.instances }}"

  - name: Create Facts for F5 configuration
    set_fact:
      f5_private_ip: "{{ item.private_ip_address }}"
      cacheable: true
    when: item.tags.function == ec2_f5_tag
    loop: "{{ ec2.instances }}"

  - name: Create security group with F5 defined
    ec2_group:
      name: "{{ ec2_sg_name }}"
      description: "DevSecOps Demo Security Group"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: "{{ hostvars.localhost.f5_private_ip + '/32' | default('0.0.0.0/0') }}"
    when: hostvars['localhost']['f5_private_ip'] is defined

  - name: Create security group no F5 deployed
    ec2_group:
      name: "{{ ec2_sg_name }}"
      description: "DevSecOps Demo Security Group"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: "0.0.0.0/0"
    when: hostvars['localhost']['f5_private_ip'] is not defined
