---
- name: configure F5
  hosts: localhost
  gather_facts: false

  vars:
  # TODO secure passwords
    # validate_certs: no
    # username: redhat
    # password: 9876tjYbsj567
    # state: present

  tasks:

    - name: Gather facts
      ec2_instance_facts:
      register: ec2
      tags:
      - debug
      delegate_to: localhost

    - name: Debug ec2
      debug:
        var: ec2
      tags:
        - debug
        - debug_ec2
      delegate_to: localhost

    # - name: Create pools
    #   bigip_pool:
    #     name: AnsibleJuiceShopPool
    #     lb_method: round-robin
    #     state: "{{ state }}"
    #     monitors: ['/Common/tcp']
    #     monitor_type: and_list
    #     # server_port: 8443
    #     provider:
    #       user: "{{ username }}"
    #       password: "{{ password }}"
    #       server: 108.128.213.140
    #       server_port: 8443
    #       validate_certs: "{{ validate_certs }}"
    #       transport: rest
    #   delegate_to: localhost 
    #   tags:
    #     - create_pool

    # - name: CreatePoolMember1
    #   bigip_pool_member:
    #     pool: AnsibleJuiceShopPool
    #     host: 10.1.20.102
    #     port: 80
    #     state: "{{ state }}"
    #     provider:
    #       user: "{{ username }}"
    #       password: "{{ password }}"
    #       server: 10.1.20.240
    #       validate_certs: "{{ validate_certs }}"
    #       transport: rest

    - name: CreatePoolMember2
      bigip_pool_member:
        pool: AnsibleJuiceShopPool
        host: 172.31.30.94
        port: 3000
        state: "{{ state }}"
        provider:
          user: "{{ username }}"
          password: "{{ password }}"
          server: 108.128.213.140
          server_port: 8443
          validate_certs: "{{ validate_certs }}"
          transport: rest
 
    # - name: CreatePoolMember3
    #   bigip_pool_member:
    #     pool: AnsibleJuiceShopPool
    #     host: 10.1.20.102
    #     port: 82
    #     state: "{{ state }}"
    #     provider:
    #       user: "{{ username }}"
    #       password: "{{ password }}"
    #       server: 10.1.20.240
    #       validate_certs: "{{ validate_certs }}"
    #       transport: rest

    - name: CreateVS
      bigip_virtual_server:
        description: AnsibleJuiceShopVIP
        destination: 172.31.19.43
        name: AnsibleJuiceShopVS
        pool: AnsibleJuiceShopPool
        port: 443
        snat: Automap
        all_profiles:
          - http
          - clientssl
        #   - websecurity
        # all_policies:
        #   - asm_auto_l7_policy__HackazonVS_HTTP
        provider:
          user: "{{ username }}"
          password: "{{ password }}"
          server: 108.128.213.140
          server_port: 8443
          validate_certs: "{{ validate_certs }}"
          transport: rest

    # - name: assign security logging profile to VS
    #   bigip_command:
    #     commands: 'modify ltm virtual AnsibleJuiceShop security-log-profiles replace-all-with { LogAllDDoS }'
    #     server: 108.128.213.140
    #     user: "{{ username }}"
    #     password: "{{ password }}"
