---
# TODO add checks for vars and state if ec2 instances
- name: configure F5
  hosts: localhost
  connection: local
  gather_facts: true
  # vars_files:
  #   - ./local/vars/vault_aws_vars.yml
  #   - ./local/vars/ec2_vars.yml

  tasks:
  - name: Gather EC2 facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      # aws_access_key: "{{ aws_access_key_id }}"
      # aws_secret_key: "{{ aws_secret_access_key }}"
    register: ec2
    tags:
     - ec2_facts

  # - name: Debug ec2 firewall
  #   debug:
  #     msg: "IP {{ item.public_ip_address }}"
  #   when: item.tags.function == ec2_firewall_tag
  #   loop: "{{ ec2.instances }}"
  #   loop_control:
  #     label: "{{ item.public_ip_address }} "
  #   tags:
  #     - debug
  #     - debug_firewall

  # - name: Debug ec2 instances IP
  #   debug:
  #     msg: "INternal IP {{ item.private_ip_address }}"
  #   when: item.tags.function == ec2_webserver_tag
  #   loop: "{{ ec2.instances }}"
  #   loop_control:
  #     label: "{{ item.public_dns_name }} "
  #   tags:
  #     - debug
  #     - debug_instances

  - name: Create Facts for F5 configuration
    set_fact:
      f5_public_ip: "{{ item.public_ip_address }}"
      f5_private_ip: "{{ item.private_ip_address }}"
      cacheable: true
    when: (item.tags.function == ec2_f5_tag) and (item.state.name == "running")
    loop: "{{ ec2.instances }}"
    failed_when: ec2.instances == ""
    tags:
      - f5_facts
    
  # - name: F5 facts var
  #   debug:
      # var: f5_facts

  - name: Debug facts
    debug:
      var: item.state.name
      # verbosity: 2
    when: (item.tags.function == ec2_webserver_tag) and (item.state.name == "running")
    loop: "{{ ec2.instances }}"
    
  - name: Create Pool
    bigip_pool:
      name: AnsibleJuiceShopPool
      lb_method: round-robin
      state: "{{ ec2_f5_state }}"
      monitors: ['/Common/tcp']
      monitor_type: and_list
      provider:
        user: "{{ user }}"
        password: "{{ password }}"
        server: "{{ hostvars.localhost.f5_public_ip }}"
        server_port: 8443
        validate_certs: "{{ ec2_validate_certs }}"
        transport: rest
    tags:
      - create_pool


  - name: Create Pool Members
    bigip_pool_member:
      pool: AnsibleJuiceShopPool
      host: "{{ item.private_ip_address }}"
      port: 3000
      state: "{{ ec2_f5_state }}"
      provider:
        server_port: 8443
        user: "{{ user }}"
        password: "{{ password }}"
        server: "{{ hostvars.localhost.f5_public_ip }}"
        validate_certs: "{{ ec2_validate_certs }}"
        transport: rest
    when: (item.tags.function == ec2_webserver_tag) and (item.state.name == "running")
    loop: "{{ ec2.instances }}"
    tags:
      - create_pool

  - name: CreateVS
    bigip_virtual_server:
      description: AnsibleJuiceShopVIP
      destination: "{{ hostvars.localhost.f5_private_ip }}"
      name: AnsibleJuiceShopVS
      pool: AnsibleJuiceShopPool
      port: 443
      snat: Automap
      all_profiles:
        - http
        - clientssl
      #   - websecurity
      # all_policies:
      #   - asm_auto_l7_policy__HackazonVS_HTTP
      provider:
        user: "{{ user }}"
        password: "{{ password }}"
        server: "{{ hostvars.localhost.f5_public_ip }}"
        server_port: 8443
        validate_certs: "{{ ec2_validate_certs }}"
        transport: rest
    tags:
      - f5_vs

    # - name: assign security logging profile to VS
    #   bigip_command:
    #     commands: 'modify ltm virtual AnsibleJuiceShop security-log-profiles replace-all-with { LogAllDDoS }'
    #     server: 108.128.213.140
    #     user: "{{ username }}"
    #     password: "{{ password }}"
