---
- name: Configure F5 WAF
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Gather EC2 facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      filters:
        instance-state-name: ["running","shutting-down", "stopping", "stopped"]
    register: ec2
    tags:
     - ec2_facts

  - name: Create Facts for F5 configuration
    set_fact:
      f5_public_ip: "{{ item['public_ip_address'] }}"
      f5_private_ip: "{{ item['private_ip_address'] }}"
      cacheable: true
    when: (item.tags.function == ec2_f5_tag) 
    loop: "{{ ec2.instances }}"
    tags:
      - f5_facts

  - name: CreateVS with WAF
    bigip_virtual_server:
      description: VIP
      destination: "{{ hostvars['localhost']['f5_private_ip'] }}"
      name: "{{ f5_vs_name }}"
      pool: "{{ f5_pool_name }}"
      port: "443"
      snat: Automap
      default_persistence_profile: "source_addr"
      security_log_profiles: "Hackazon_Logging"
      all_profiles:
        - http
        - Hackazon_Client_SSL
        - websecurity
      all_policies:
        - Hackazon_Policy
      provider:
        user: "{{ user }}"
        password: "{{ password }}"
        server: "{{ hostvars['localhost']['f5_public_ip'] }}"
        server_port: 8443
        validate_certs: "{{ ec2_validate_certs }}"
        transport: rest
    tags:
      - f5_create_vs
