---
- name: Deploy Jenkins Server
  hosts: ciservers
  become: true
  vars_files:
    - vars/rhsm_vars.yml
    - vars/jenkins_vars.yml

  roles:
  - role: openstack.redhat-subscription
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
      
  # - geerlingguy.repo-epel
  - role: geerlingguy.jenkins
    vars_files:
    - vars/jenkins_vars.yml

  tasks:
  - name: Enable Jenkins http 8080
    firewalld:
      state: enabled
      permanent: true
      port: 80/tcp
  - name: Restart Jenkins service
    service:
      name: jenkins
      state: restarted
      enabled: true

  tags:
    - jenkins
    - devsecops