---
- name: Install SonarQube
  hosts: qcservers
  become: true
  vars_files:
    - vars/rhsm_vars.yml
    - vars/sonar_vars.yml

  roles:
  - role: openstack.redhat-subscription
    tags:
      - sonar_rhsm
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"

  tasks:
  - name: Install package dependencies
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
    tags:
      - sonar_pkg_dependencies
  
  - name: Install SonarQube
    include_role: 
      name: lrk.sonarqube
    tags:
      - sonar_install

  - name: Allow external traffic port 9000
    firewalld:
      state: enabled
      permanent: true
      port: 9000/tcp
    tags:
      - sonar_firewall

  - name: Reload firewalld service
    service:
      name: firewalld
      state: reloaded
      enabled: true
    tags:
      - sonar_firewall_restart
  tags:
    - sonar_deploy
    - devsecops
