---
- name: Install SonarQube
  hosts: all
  become: false

  pre_tasks:
    - name: Install package dependencies.
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - unzip
#   vars:
#     sonar_path: '/opt/sonar'
#   pre_tasks:
#     # delete sonar installed on previous run to prevent plugins conflict in case if any plugin is updated
#     - name: delete sonar
#       file:
#         path: '{{ sonar_path }}'
#         state: absent
  # tasks:
  # - name: Install EPEL Repo
  #   yum:
  #     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  #     state: present
  # - name: Install PostgreSQL11 Repo
  #   yum:
  #     name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  #     state: present

  roles:
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
    vars:
      java_packages: 
        - java-1.8.0-openjdk
  - role: lrk.sonarqube
    vars:
      sonar_version: 7.7
  # - role: anxs.postgresql
  #   become: false
  #   vars:
  #     postgresql_users:
  #       - name: sonar
  #         pass: sonar
  #     postgresql_databases:
  #       - name: sonar
  #         owner: sonar
  # - role: jdauphant.ssl-certs
  #   vars:
  #     ssl_certs_common_name: '{{ ansible_fqdn }}'
  #     ssl_certs_path_owner: root
  #     ssl_certs_path_group: root
  #     ssl_certs_mode: 0755
  # - role: nginxinc.nginx
  # - role: lean_delivery.sonarqube
  #   vars:
  #     sonar_install_optional_plugins: True
  #     sonar_check_url: 'https://{{ ansible_fqdn }}'
  # post_tasks:
  # - name: delete default nginx config
  #   file:
  #     path: /etc/nginx/conf.d/default.conf
  #     state: absent
  # - name: restart, enable nginx
  #   service: 
  #     name: nginx
  #     state: restarted
  #     enabled: True
