---
- name: Configure Tower for DevSecOps Demo
  hosts: adminservers
  become: true

  tasks:
  - name: Create AWS credential
    tower_credential:
      name: AWS Credentials
      description: AWS Credentials DevSecOps Demo
      kind: aws
      organization: Default
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      username: "{{ aws_access_key_id }}"
      password: "{{ aws_secret_access_key }}"
      state: present

