---
# TODO add additional creds
# no option for insights project type. need to use command
# lookup ssh key from variable not working

- name: Configure Tower for DevSecOps Demo
  hosts: adminservers
  become: false
  gather_facts: false

  tasks:
  - name: Create RHV credential
    tower_credential:
      name: RHV Credential
      description: RHV Credentials DevSecOps Demo
      kind: rhv
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      host: "{{ rhv_auth_url }}"
      username: "{{ rhv_cred_user }}"
      password: "{{ rhv_cred_password }}"
      user: admin
      state: present
      validate_certs: false
    tags:
      - tower-config
      - rhv-credential

  - name: Create AWS credential
    tower_credential:
      name: AWS Credentials
      description: AWS Credentials DevSecOps Demo
      kind: aws
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      username: "{{ aws_access_key_id }}"
      password: "{{ aws_secret_access_key }}"
      user: admin
      state: present
      validate_certs: false
    tags:
      - tower-config
      - aws-credential
  
  - name: Create Demo SSH Key Credential
    tower_credential:
      name: Demo SSH Key 
      description: Demo SSH Key DevSecOps Demo
      kind: ssh
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      username: "{{ ssh_key_username }}"
      ssh_key_data: "{{ lookup('file', '/Users/craig/.ssh/ans_demo_key') }}"
      #ssh_key_data: "{{ lookup('file', ssh_key_file) }}"
      user: admin
      state: present
      validate_certs: false
    tags:
      - tower-config
      - demo-ssh-key

  - name: debug private key
    debug:
      var: ssh_key_file
      verbosity: 2
    tags:
      - tower-config
      - debug-private-key

  - name: Create Insights Credential
    tower_credential:
      name: Insights Credential
      description: Craig Insights Credentials for Insghts Demo
      kind: insights
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      username: "{{ insights_cred_user }}"
      password: "{{ insights_cred_password }}"
      user: admin
      state: present
      validate_certs: false
 
  - name: Create Insights Inventory
    tower_inventory:
      name: Insights Inventory
      description: Craig Insights Inventory
      state: present
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      validate_certs: false
    tags:
      - tower-config
      - insights-inventory

  - name: Create Insights Inventory Source
    tower_inventory_source:
      name: Insights RHV Inventory Source
      description: Insights RHV Inventory Source
      state: present
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      credential: rhev
      source: rhv
      inventory: Insights Inventory
      overwrite: true
      validate_certs: false
    tags:
      - tower-config
      - insights-inventory-source

  - name: Create RHV Inventory
    tower_inventory:
      name: RHV MBU Inventory
      description:  RHV MBU Inventory
      state: present
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      validate_certs: false
    tags:
      - tower-config
      - rhv-inventory

  - name: Create RHV Inventory Source
    tower_inventory_source:
      name: RHV MBU Inventory Source
      description: RHV MBU Inventory Source
      state: present
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      credential: RHV Credential
      source: rhv
      inventory: RHV MBU Inventory
      overwrite: true
      validate_certs: false
    tags:
      - tower-config
      - rhv-inventory-source


        #- name: Create Insights Project
        #tower_project:
        # name: "Insights Project"
        #state: present
        #description: Ansible Tower Insights Integration Project
        #organization: "{{ tower_organization }}"
        #scm_credential: Insights Credential
        #scm_type: insights
  
  - name: Create Insights Project
    command: >
      tower-cli project create 
      --name "Insights Project" 
      --description "Insights Demo Project" 
      --scm-type insights 
      --scm-credential "Insights Credential"
      --tower-username "{{ tower_username }}" 
      --tower-password "{{ tower_password }}" 
      --organization "{{ tower_organization }}"
      --tower-host "{{ tower_host }}"
      --insecure
    tags:
      - tower-config
      - insights-project

  - name: Create Insights Scan Project
    tower_project:
      name: Insights Scan Project
      tower_host: "{{ tower_host }}"
      organization: "{{ tower_organization }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      state: present
      description: Ansible Tower Insights Scan Project
      scm_type: git
      scm_url: https://github.com/ansible/awx-facts-playbooks
      scm_update_cache_timeout: 120
      validate_certs: false
    tags:
      - tower-config
      - insights-scan-project
  
  - name: Create Insights Scan Job Template
    tower_job_template:
      name: Insights Scan Template
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      playbook: scan_facts.yml
      project: Insights Scan Project
      fact_caching_enabled: true
      inventory: Insights Inventory
      job_type: run
      credential: Demo SSH Key
      validate_certs: false
    tags:
      - tower-config
      - insights-job-template
