#EC2 vars
ec2_region: eu-west-1
ec2_f5_tag: f5firewall
ec2_webserver_tag: webserver
ec2_f5_state: present
ec2_webserver_teardown_state: absent
ec2_f5_teardown_state: stopped
ec2_keyname: devsecopskey
ec2_sg_name: sg_devsecops
ec2_instance_type: t2.medium
ec2_ami: ami-7c491f05
ec2_count: 3
f5_vs_name: AnsibleJuiceShopVS
f5_pool_name: AnsibleJuiceShopPool
f5_validate_certs: false

#Tower vars
f5_user: "f5 username"
f5_password: "f5 password"
tower_host: tower.vagrant.local
tower_username: admin
tower_password: admin
tower_organization: JuiceShop
aws_username: "aws username"
aws_password: "aws password"
aws_ssh_user: ec2-user
aws_pvt_key: '/$HOME/.ssh/"AWS pvt key"'
jenkins_pwd: admin
jenkins_user: jenkins
pri_galaxy_token: "automation hub token"
pri_galaxy_url: https://cloud.redhat.com/api/automation-hub/
pri_galaxy_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

#GitHub
github_pvt_key: '/$HOME/.ssh/"pvt github key"'
github_scm_url: "your repo e.g. https://github.com/craig-br/ans-tower-devsecops.git"

# Vars to configure Tower password
aw_home: /var/lib/awx
aw_user: awx
aw_group: awx
reset_playbook_dir: '/etc/tower/reset'
admin_password_file: '{{reset_playbook_dir}}/.admin_password'
reconfigured_file: '{{reset_playbook_dir}}/.reconfigured'


# Vars for initial config of vagrant hosts
demo_ssh_key_username: vagrant
demo_ssh_key_file: '/$HOME/.ssh/"additional ssh pub key"'
demo_ssh_pvt_key_file: '/$HOME/.ssh/"ssh pvt key"'