---
- name: Deploy Jenkins Server
  hosts: ciservers
  become: true

  roles:
  - role: openstack.redhat-subscription
    when: "ansible_os_family == 'RedHat'"
  - role: geerlingguy.java
    when: "ansible_os_family == 'RedHat'"
  - role: geerlingguy.jenkins
  - role: geerlingguy.nodejs

  tasks:
  - name: Install base packages
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ base_packages }}"
    tags:
      - jenkins_pkg_dependencies

  - name: Install npm dependences
    npm:
      name: "{{ item.name }}"
      version: "{{ item.version | default('latest') }}"
      global: "{{ item.global | default('false') }}"
      path: "{{ item.path }}"
    loop: "{{ npm_packages }}"
    tags:
      - jenkins_npm_packages

  - name: Enable Jenkins http 8080
    firewalld:
      state: enabled
      permanent: true
      port: 8080/tcp
    tags:
      - jenkins_firewall
  - name: Reload firewalld service
    service:
      name: firewalld
      state: reloaded
      enabled: true
    tags:
      - jenkins_restart

  tags:
    - jenkins
    - devsecops