---
- name: Install SonarQube
  hosts: qcservers
  become: true

  roles:
  - role: openstack.redhat-subscription
    tags:
      - sonar-rhsm
  - role: geerlingguy.java

  tasks:
  - name: Install package dependencies
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ sonar_packages }}"
    tags:
      - sonar_pkg_dependencies
  
  - name: Install SonarQube
    include_role: 
      name: lrk.sonarqube
    tags:
      - sonar_install

  - name: Allow external traffic port 9000
    firewalld:
      state: enabled
      permanent: true
      port: 9000/tcp
    tags:
      - sonar_firewall

  - name: Reload firewalld service
    service:
      name: firewalld
      state: reloaded
      enabled: true
    tags:
      - sonar_firewall_restart
  tags:
    - sonar_deploy
    - devsecops
